taskd:
    image: jdeighton/taskd:latest
    volumes:
        - ./taskd:/var/taskd
    ports:
        - "53589:53589"
    environment:
        CERT_CN: "taskd"
        CERT_ORGANIZATION: "jdeighton"
        CERT_COUNTRY: "US"
        CERT_STATE: "NY"
        CERT_LOCALITY: "New York"
    restart: always
